### ISSUE TITLE
Another rabbithole of ABP

### ISSUE THREAD

**Issue by KadTheHunter** [hschwar/AccurateBlockPlacementOld#1]
I recently forked and updated a fork of ABP to 1.20.1 [(here's my version](https://github.com/KadTheHunter/AccurateBlockPlacement)). I believe it ties into Flouricks version somewhere, although I admit I can't find him in the commits.

Nevertheless, the top level repository (and all subsequent forks) contains a link to the [CurseForge page](https://legacy.curseforge.com/minecraft/mc-mods/accurate-block-placement) of the original mod, which has a link to Flouricks (now vanished) repository.

Not sure how useful any of this is (or if it's even what you're looking for), but I figured I may as well bring it up, just in case :)

**Comment by hschwar** [comment]
Perfect! It seems that it was forked just before the original's source code was removed, and it is completely up to date.
I noticed that you made some other changes that seem cool.

Would it be possible to use your repository for the ABP Reborn modpage?
The one here that I have is pretty empty and is forked from an older 1.17 version of ABP.

**Comment by KadTheHunter** [comment]
Sure, I could even transfer ownership if needed. I'll still be keeping an eye on ABP to update it if nobody else does, but I have no intention of upgrading it beyond that, so it's probably better in your hands.

**Comment by hschwar** [comment]
That would be great, with access to it I could migrate everything from this repo to yours and maintain it from there.

**Comment by KadTheHunter** [comment]
@hschwar transfer requested, had to rename repo to [AccurateBlockPlacement Reborn](https://github.com/KadTheHunter/AccurateBlockPlacement-Reborn) because AccurateBlockPlacement is already owned by you lol
